version: "4.0"

services:
  my-site-server:
    build:
      context: .
      dockerfile: dockerfile
    command: node app.js
    volumes:
      - /home/lys/buildMission:/home/lys/buildMission
    ports:
      - "3000:3000"
    restart: always
